#!/bin/bash

METADATA=$(oc-metadata --cached)

metadata() {
    key=$1
    echo "$METADATA" | grep "^$key=" | cut -d= -f2 | sed "s/^['\"]//;s/['\"]$//"
}

PUBLIC_IP=$(metadata PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,

Welcome to the Ampache image, available at:

- http://${PUBLIC_IP}/

The MySQL credentials are:

- login: root 
- password: {mysql_root_password}

Your website configuration lies at:
- /etc/nginx/sites-available/ampache

Enjoy!
EOF